CREATE DATABASE IF NOT EXISTS comkaraka;
USE comkaraka;

CREATE TABLE IF NOT EXISTS
replies (
  reply_id INT PRIMARY KEY AUTO_INCREMENT,
  comment_id INT NOT NULL,
  user_id VARCHAR(20) NOT NULL,
  content TEXT NOT NULL,
  is_removed BOOLEAN,
  posted_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS
comments (
  comment_id INT PRIMARY KEY AUTO_INCREMENT,
  article_id INT NOT NULL,
  user_id VARCHAR(20) NOT NULL,
  content TEXT NOT NULL,
  is_removed BOOLEAN,
  posted_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS
articles (
  article_id INT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(20) NOT NULL,
  title TEXT NOT NULL,
  category VARCHAR(255) NOT NULL,
  catevalue TEXT,
  content TEXT NOT NULL,
  posted_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS
users (
  user_id VARCHAR(20) PRIMARY KEY,
  user_pw VARCHAR(255) NOT NULL,
  user_name VARCHAR(50),
  user_addi_info TEXT,
  user_tel VARCHAR(30),
  user_email VARCHAR(100),
  user_img TEXT,
  is_admin BOOLEAN,
  is_alive BOOLEAN,
  registered_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS
fcmtokens (
  value VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(20) NOT NULL,
  created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);